### ISSUE TITLE
Null values are not handled correctly in 'PacketBuffer' and packets in general

### ISSUE THREAD

**Issue by VoltexYT** [GoMint/ProxProx#39]
```
16:41:55.214 [TCP Threads] INFO  io.gomint.proxprox.network.UpstreamConnection - Connected to 127.0.0.1:19133
16:42:39.145 [TCP Threads] INFO  io.gomint.proxprox.network.UpstreamConnection - Connected to 127.0.0.1:19134
16:42:39.145 [TCP Threads] INFO  io.gomint.proxprox.network.DownstreamConnection - Player io.gomint.proxprox.network.UpstreamConnection@229a6a88 disconnected from server io.gomint.proxprox.network.DownstreamConnection@b01b2c25: Transfer to new server
16:42:39.145 [TCP Threads] INFO  io.gomint.proxprox.network.DownstreamConnection - Disconnected downstream...
16:42:42.167 [epollEventLoopGroup-2-4] INFO  io.gomint.proxprox.network.SocketEventListener - Disconnected upstream: -6919005209949525182
16:42:42.167 [epollEventLoopGroup-2-4] INFO  io.gomint.proxprox.network.DownstreamConnection - Disconnecting DownStream for e26a0394-2856-3d54-8cec-515c644a05d1
16:42:42.169 [TCP Threads] INFO  io.gomint.proxprox.network.UpstreamConnection - Connected to 127.0.0.1:19133
16:42:42.172 [epollEventLoopGroup-2-4] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
        at io.gomint.jraknet.PacketBuffer.writeString(PacketBuffer.java:482) ~[ProxProx.jar:?]
        at io.gomint.proxprox.network.protocol.PacketText.serialize(PacketText.java:56) ~[ProxProx.jar:?]
        at io.gomint.proxprox.network.UpstreamConnection.send(UpstreamConnection.java:584) ~[ProxProx.jar:?]
        at io.gomint.proxprox.network.UpstreamConnection.sendMessage(UpstreamConnection.java:645) ~[ProxProx.jar:?]
        at io.gomint.proxprox.network.DownstreamConnection.internalClose(DownstreamConnection.java:627) ~[ProxProx.jar:?]
        at io.gomint.proxprox.network.DownstreamConnection.disconnect(DownstreamConnection.java:605) ~[ProxProx.jar:?]
        at io.gomint.proxprox.network.SocketEventListener.onSocketEvent(SocketEventListener.java:99) ~[ProxProx.jar:?]
        at io.gomint.jraknet.Socket.propagateEvent(Socket.java:127) ~[ProxProx.jar:?]
        at io.gomint.jraknet.ServerSocket.propagateConnectionClosed(ServerSocket.java:308) ~[ProxProx.jar:?]
        at io.gomint.jraknet.ServerConnection.propagateConnectionClosed(ServerConnection.java:123) ~[ProxProx.jar:?]
        at io.gomint.jraknet.Connection.handleDisconnectionNotification(Connection.java:1360) ~[ProxProx.jar:?]
        at io.gomint.jraknet.Connection.pushReceivedPacket(Connection.java:1300) ~[ProxProx.jar:?]
        at io.gomint.jraknet.Connection.handleConnectedDatagram(Connection.java:1238) ~[ProxProx.jar:?]
        at io.gomint.jraknet.Connection.handleDatagram(Connection.java:873) ~[ProxProx.jar:?]
        at io.gomint.jraknet.ServerConnection.handleDatagram(ServerConnection.java:69) ~[ProxProx.jar:?]
        at io.gomint.jraknet.ServerSocket.handleDatagram(ServerSocket.java:214) ~[ProxProx.jar:?]
        at io.gomint.jraknet.ServerSocket$1.channelRead(ServerSocket.java:123) ~[ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [ProxProx.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [ProxProx.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:480) [ProxProx.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [ProxProx.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [ProxProx.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [ProxProx.jar:?]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [ProxProx.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
16:42:45.919 [epollEventLoopGroup-2-4] INFO  jRaknet - Fully established new incoming connection: /79.252.17.2:65514
16:42:46.103 [main] INFO  io.gomint.proxprox.network.UpstreamConnection - Login version number: 291
16:42:46.121 [main] INFO  io.gomint.proxprox.jwt.MojangChainValidator - Provided trusted key: MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE8W8tdvYLA7yYig5hev5V9EPH6Bo+c/UyxR3JDosvhsrjgi4m8y6CUH6HUHfVqf6Z5KKIjmtZhjXWyXrIhivErVj1HcF6/vD8v1Gxqwg9m01+AfvPSuoc3GHKnJX3fMzL
16:42:46.121 [main] INFO  io.gomint.proxprox.jwt.MojangChainValidator - Provided trusted key: MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEPgppk5f79bsA4aNHFJYwVFQ9PXNdKjujYRkqmSjHy8Fk4wZ0eURZFE8OuXrDgUvfkNL5a2cTdUqbiUhatLppQhHTM823rcP7rHFDY6uMAY/DM8dJjas9kr9QIif+zfjJ
16:42:46.121 [main] INFO  io.gomint.proxprox.jwt.MojangChainValidator - Provided trusted key: MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE8ELkixyLcwlZryUQcu1TvPOmI2B7vX83ndnWRUaXm74wFfa5f/lwQNTfrLVHa2PmenpGI6JhIMUJaWZrjmMj90NoKNFSNBuKdm8rYiXsfaz3K36x/1U26HpG0ZxK/V1V
16:42:46.121 [main] INFO  io.gomint.proxprox.network.UpstreamConnection - Got valid XBOX Live Account ID: 2535433427872494
16:42:46.129 [main] INFO  io.gomint.proxprox.network.UpstreamConnection - Logged in as VoltexDE (UUID: e26a0394-2856-3d54-8cec-515c644a05d1; GUID: -7946644849116389021)
16:42:46.140 [main] INFO  io.gomint.proxprox.network.UpstreamConnection - Crafted JWT for client: eyJ4NXUiOiJNSFl3RUFZSEtvWkl6ajBDQVFZRks0RUVBQ0lEWWdBRUJEMDR1VlwvTnpnZ29NbVEzeHRYbm5sZDN2WHNyQ2JDam1jY0dQOURQMG5pM1wvdG42WkdXWTcrMGZWWnBLT252S1QyUDJJVE9WQmx1ZHMrSXlKcVh6Q1FVNU9HT0xaZnRReHNvb3Z6ZFMrOHVwa1phSytjWjNHZzNcL1pBaU1qeXdPIiwiYWxnIjoiRVMzODQifQ==.eyJzYWx0IjoiOUdKck5FeTNhZk9ZZ2Y0cW51K0FTZz09In0=.-SyHcNSpShZiUP7Ekex-ADjD2eupGPbSeWz-64DikH6UWSLEGvlm2GGYtoOYDwTuP3SrU1K6acy-v2PlIKRHjQB1DExcTaS2V10mgSKR_ZsonhjFVkH6HWEiB9-rI_0y
16:42:47.007 [TCP Threads] INFO  io.gomint.proxprox.network.UpstreamConnection - Connected to 127.0.0.1:19133
16:42:47.097 [TCP Threads] INFO  io.gomint.proxprox.network.DownstreamConnection - Player io.gomint.proxprox.network.UpstreamConnection@229a6a88 disconnected from server io.gomint.proxprox.network.DownstreamConnection@b01b2c25: Player already logged in on this server
16:42:47.098 [TCP Threads] INFO  io.gomint.proxprox.network.DownstreamConnection - Disconnected downstream...

```

**Comment by Shad0wCore** [comment]
Either way, it's clearly ProxProx's fault. You tried to send something to somebody and passed `null` to a function somewhere. By default, ProxProx should default-vaue null values to prevent NPEs (NullPointerException) and unwanted behaviour to occur.

Thank you for creating an issue.

**Comment by Shad0wCore** [comment]
The fix is pretty obvious and easy to implement. There are two ways to fix this:
- Assign null values a default value
- Use `@NonNull` provided by Lombok to force users to not pass null values

**Comment by Janmm14** [comment]
this issue is not caused by a plugin

using current source files, the line numbers seem to not match

**Comment by Shad0wCore** [comment]
That's weird. So, the message is not send by a plugin but by `SocketEventListener` which passed the following string: `Connection closed`. There's no actual null value passed but still results in an NPE.

**Comment by Janmm14** [comment]
The npe is unable to happen at line 482 of the PacketBuffer in current jraknet code (the class was last changed in 2017)

**Comment by Shad0wCore** [comment]
Issue's closed due to changes have been made to the origin ProxProx repository. If the exception occurs again please create an new issue. Also, try to indicate if you're using the current (newest) ProxProx build.

Issue closed.
