### ISSUE TITLE
UpstreamConnection#flushSendQueue() tries to access 'executor' field after connection died/was closed

### ISSUE THREAD

**Issue by voltexde** [GoMint/ProxProx#40]
```
05:46:20.541 [TCP Threads] ERROR io.gomint.proxprox.network.tcp.ConnectionHandler - Caught exception in connection (connected to 127.0.0.1:14002) handling:
java.lang.NullPointerException
        at io.gomint.proxprox.network.UpstreamConnection.flushSendQueue(UpstreamConnection.java:836) ~[ProxProx.jar:?]
        at io.gomint.proxprox.network.tcp.ConnectionHandler.channelRead0(ConnectionHandler.java:66) ~[ProxProx.jar:?]
        at io.gomint.proxprox.network.tcp.ConnectionHandler.channelRead0(ConnectionHandler.java:16) ~[ProxProx.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [ProxProx.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [ProxProx.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [ProxProx.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [ProxProx.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [ProxProx.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [ProxProx.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [ProxProx.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797) [ProxProx.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [ProxProx.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [ProxProx.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [ProxProx.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by Shad0wCore** [comment]
Apparently somebody or something tries to send something after the connection died or was closed. The exception occurrs because when `AbstractConnection#close()` is called, the function nullifies the `PostProcessExecutor executor` field. 

`UpstreamConnection.flushSendQueue(UpstreamConnection.java:836)` tries to call the function `PostProcessExecutor#addWork()` but fails due to the field's value being null. 

Imho this is clearly a bug and needs a fix. Maybe implementing an `if`-statement checking whether or not the connection is closed.

Thank you for creating an issue.
