### ISSUE TITLE
Player join bug || java.lang.NullPointerException

### ISSUE THREAD

**Issue by voltexde** [GoMint/ProxProx#51]
```
12:35:06.347 [main] INFO  io.gomint.proxprox.ProxProxProxy - Starting ProxProxProxy v1.0.0
12:35:06.541 [main] INFO  io.gomint.proxprox.ProxProxProxy - Bound to 0.0.0.0:19132
12:35:19.434 [epollEventLoopGroup-2-1] INFO  jRaknet - Fully established new incoming connection: /MYIP
12:35:19.447 [epollEventLoopGroup-2-1] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
        at io.gomint.proxprox.network.AbstractConnection.setup(AbstractConnection.java:59) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.proxprox.network.UpstreamConnection.setup(UpstreamConnection.java:149) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.proxprox.network.UpstreamConnection.<init>(UpstreamConnection.java:143) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.proxprox.network.SocketEventListener.onSocketEvent(SocketEventListener.java:72) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.Socket.propagateEvent(Socket.java:127) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.ServerSocket.propagateFullyConnectedConnection(ServerSocket.java:304) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.ServerConnection.propagateFullyConnected(ServerConnection.java:143) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.Connection.setState(Connection.java:566) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.ServerConnection.handleNewIncomingConnection(ServerConnection.java:260) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.ServerConnection.handlePacket0(ServerConnection.java:113) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.Connection.pushReceivedPacket(Connection.java:1326) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.Connection.handleConnectedDatagram(Connection.java:1261) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.Connection.handleDatagram(Connection.java:890) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.ServerConnection.handleDatagram(ServerConnection.java:70) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.ServerSocket.handleDatagram(ServerSocket.java:222) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.gomint.jraknet.ServerSocket$1.channelRead(ServerSocket.java:125) ~[ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:480) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:394) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [ProxProx.jar:1.0-SNAPSHOT-"3f5c7ec"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

```

**Comment by Shad0wCore** [comment]
Null pointer exception fixed by latest commit. Should work now.
